version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    container_name: product-aggregation-app
    ports:
      - '${PORT:-8000}:${PORT:-8000}'
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - API_KEY=${API_KEY}
      - PORT=${PORT:-8000}
    networks:
      - shared-network

    restart: always

networks:
  shared-network:
    external: true
